from txt2gest_fun.drawSentenceGesture import drawSentenceGesture
from txt2gest_fun.gestureToPlot import gestureToPlot
from txt2gest_fun.docParse import parse_doc

text = """
have,
think,
explain,
know,
recieve,
take,
give,
throw,
hold,
stand,
see,
speak,
eat,
hear,
walk,
is (temporal),
run,
kick,
time,
space,
body,
where,
when,
before,
after,
before(temporal),
after(temporal),
here,
there,
now,
then,
i,
we,
you,
they,
it,
will,
do,
be,
I am,
I will eat,
I am eating ,
I run ,
I ran,
I will be running,
You are,
You will eat,
You run,
You ran,
They will be running,
They eat, 
They ate, 
They did,
They are,
We are here,
You were there,
They will be here,
I thought,
I thought you have eaten here before,
I heard you speak before,
I walked here before you ran,
They were seeing you,
I kicked you knowing you had heard them,
Then they threw you,
You took it before running there,
They were seeing you,
I kicked you knowing you had heard them,
I walked here, before you ran,
Then they threw you,
You took it before running there,
I walked here before you ran,
were they seeing you,
I kicked you knowing you had heard them,
did they threw you,
You took it before running there,
They were seeing you,
I thought you have eaten here before,
I heard you speak before,
They ran here
"""
prompts=text.split(',')
with open('training_data.txt', 'w') as f:
    for prompt in prompts:
        [phrases,lemmas,meta_datas,POS] = parse_doc(prompt.strip())
        gestures=drawSentenceGesture(phrases,lemmas,meta_datas,POS)
        for gesture in gestures:
            f.write(prompt + ":")
            f.write("".join([str(x) for x in gesture['dir_sequence'] ]))
